### ISSUE TITLE
Extend issue template for bugs and features

### ISSUE THREAD

**Issue by BioPhoton** [code-pushup/cli#720]
add plugin options:
``` yml
  - type: dropdown
    id: related-plugin
    attributes:
      label: What plugin is involved?
      multiple: false
      options:
        - none/all
        - Coverage
        - EsLint
        - Lighthouse
        - JsPackages
```
